# Config Map used: configmap.yaml in same directory

apiVersion: v1
kind: Pod
metadata:
  name: test-pod-vol
spec:
  containers:
    - name: test-container
      image: gcr.io/google_containers/busybox
      command: ["/bin/sh", "-c", "--"]
      args: ["while true; do sleep 30; done;"]
      volumeMounts:
        - name: config-volume
          mountPath: /etc/config
  volumes:
    - name: config-volume
      configMap:
        name: log-config
  restartPolicy: Never